# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import output.map_clear_area_pb2 as map__clear__area__pb2
import output.map_crosswalk_pb2 as map__crosswalk__pb2
import output.map_junction_pb2 as map__junction__pb2
import output.map_lane_pb2 as map__lane__pb2
import output.map_overlap_pb2 as map__overlap__pb2
import output.map_signal_pb2 as map__signal__pb2
import output.map_speed_bump_pb2 as map__speed__bump__pb2
import output.map_stop_sign_pb2 as map__stop__sign__pb2
import output.map_yield_sign_pb2 as map__yield__sign__pb2
import output.map_road_pb2 as map__road__pb2
import output.map_parking_space_pb2 as map__parking__space__pb2
import output.map_pnc_junction_pb2 as map__pnc__junction__pb2
import output.map_rsu_pb2 as map__rsu__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmap.proto\x12\x0c\x61pollo.hdmap\x1a\x14map_clear_area.proto\x1a\x13map_crosswalk.proto\x1a\x12map_junction.proto\x1a\x0emap_lane.proto\x1a\x11map_overlap.proto\x1a\x10map_signal.proto\x1a\x14map_speed_bump.proto\x1a\x13map_stop_sign.proto\x1a\x14map_yield_sign.proto\x1a\x0emap_road.proto\x1a\x17map_parking_space.proto\x1a\x16map_pnc_junction.proto\x1a\rmap_rsu.proto\"\x1a\n\nProjection\x12\x0c\n\x04proj\x18\x01 \x01(\t\"\xeb\x01\n\x06Header\x12\x0f\n\x07version\x18\x01 \x01(\x0c\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\x0c\x12,\n\nprojection\x18\x03 \x01(\x0b\x32\x18.apollo.hdmap.Projection\x12\x10\n\x08\x64istrict\x18\x04 \x01(\x0c\x12\x12\n\ngeneration\x18\x05 \x01(\x0c\x12\x11\n\trev_major\x18\x06 \x01(\x0c\x12\x11\n\trev_minor\x18\x07 \x01(\x0c\x12\x0c\n\x04left\x18\x08 \x01(\x01\x12\x0b\n\x03top\x18\t \x01(\x01\x12\r\n\x05right\x18\n \x01(\x01\x12\x0e\n\x06\x62ottom\x18\x0b \x01(\x01\x12\x0e\n\x06vendor\x18\x0c \x01(\x0c\"\xc4\x04\n\x03Map\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.apollo.hdmap.Header\x12*\n\tcrosswalk\x18\x02 \x03(\x0b\x32\x17.apollo.hdmap.Crosswalk\x12(\n\x08junction\x18\x03 \x03(\x0b\x32\x16.apollo.hdmap.Junction\x12 \n\x04lane\x18\x04 \x03(\x0b\x32\x12.apollo.hdmap.Lane\x12)\n\tstop_sign\x18\x05 \x03(\x0b\x32\x16.apollo.hdmap.StopSign\x12$\n\x06signal\x18\x06 \x03(\x0b\x32\x14.apollo.hdmap.Signal\x12&\n\x05yield\x18\x07 \x03(\x0b\x32\x17.apollo.hdmap.YieldSign\x12&\n\x07overlap\x18\x08 \x03(\x0b\x32\x15.apollo.hdmap.Overlap\x12+\n\nclear_area\x18\t \x03(\x0b\x32\x17.apollo.hdmap.ClearArea\x12+\n\nspeed_bump\x18\n \x03(\x0b\x32\x17.apollo.hdmap.SpeedBump\x12 \n\x04road\x18\x0b \x03(\x0b\x32\x12.apollo.hdmap.Road\x12\x31\n\rparking_space\x18\x0c \x03(\x0b\x32\x1a.apollo.hdmap.ParkingSpace\x12/\n\x0cpnc_junction\x18\r \x03(\x0b\x32\x19.apollo.hdmap.PNCJunction\x12\x1e\n\x03rsu\x18\x0e \x03(\x0b\x32\x11.apollo.hdmap.RSU')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROJECTION']._serialized_start=288
  _globals['_PROJECTION']._serialized_end=314
  _globals['_HEADER']._serialized_start=317
  _globals['_HEADER']._serialized_end=552
  _globals['_MAP']._serialized_start=555
  _globals['_MAP']._serialized_end=1135
# @@protoc_insertion_point(module_scope)
